services:
  redis:
    image: redis:latest
    container_name: learn-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    container_name: learn-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: exampledb
    volumes:
      - mongo-data:/data/db

volumes:
  redis-data:
  mongo-data: